import type { LinearIssue, LinearState } from "../../types/taskboard"

export const PRIORITY_LABELS: Record<number, { label: string; color: string }> =
	{
		0: { label: "No priority", color: "var(--dim)" },
		1: { label: "Urgent", color: "var(--task-priority-urgent)" },
		2: { label: "High", color: "var(--task-priority-high)" },
		3: { label: "Medium", color: "var(--task-priority-medium)" },
		4: { label: "Low", color: "var(--task-priority-low)" },
	}

export const STATE_TYPE_ORDER = [
	"backlog",
	"unstarted",
	"started",
	"completed",
	"cancelled",
]

export const DEMO_STATES: LinearState[] = [
	{
		id: "s1",
		name: "Backlog",
		color: "var(--task-state-backlog)",
		type: "backlog",
		position: 0,
	},
	{
		id: "s2",
		name: "Todo",
		color: "var(--task-state-todo)",
		type: "unstarted",
		position: 0,
	},
	{
		id: "s3",
		name: "In Progress",
		color: "var(--task-state-active)",
		type: "started",
		position: 0,
	},
	{
		id: "s4",
		name: "In Review",
		color: "var(--task-state-review)",
		type: "started",
		position: 1,
	},
	{
		id: "s5",
		name: "Done",
		color: "var(--task-state-done)",
		type: "completed",
		position: 0,
	},
	{
		id: "s6",
		name: "Cancelled",
		color: "var(--task-state-cancelled)",
		type: "cancelled",
		position: 0,
	},
]

export const DEMO_ISSUES: LinearIssue[] = [
	{
		id: "d1",
		identifier: "MAS-42",
		title: "Add tool-use streaming to agent responses",
		state: DEMO_STATES[2],
		priority: 1,
		url: "#",
		labels: [
			{ name: "feature", color: "var(--task-label-feature)" },
			{ name: "agents", color: "var(--task-label-agent)" },
		],
		assignee: { name: "Grayson", displayName: "Grayson" },
		createdAt: "2026-02-20T10:00:00Z",
		updatedAt: "2026-02-24T09:00:00Z",
	},
	{
		id: "d2",
		identifier: "MAS-41",
		title: "Implement RAG pipeline with pgvector embeddings",
		state: DEMO_STATES[2],
		priority: 2,
		url: "#",
		labels: [
			{ name: "feature", color: "var(--task-label-feature)" },
			{ name: "rag", color: "var(--task-state-review)" },
		],
		assignee: { name: "Grayson", displayName: "Grayson" },
		createdAt: "2026-02-19T14:00:00Z",
		updatedAt: "2026-02-23T16:00:00Z",
	},
	{
		id: "d3",
		identifier: "MAS-40",
		title: "Fix memory leak in long-running workflow executions",
		state: DEMO_STATES[3],
		priority: 1,
		url: "#",
		labels: [
			{ name: "bug", color: "var(--task-label-bug)" },
			{ name: "workflows", color: "var(--task-label-workflow)" },
		],
		assignee: { name: "Dax", displayName: "Dax" },
		createdAt: "2026-02-18T09:00:00Z",
		updatedAt: "2026-02-24T08:00:00Z",
	},
	{
		id: "d4",
		identifier: "MAS-39",
		title: "Add retry logic to MCP tool connections",
		state: DEMO_STATES[1],
		priority: 2,
		url: "#",
		labels: [
			{ name: "enhancement", color: "var(--task-label-enhancement)" },
			{ name: "mcp", color: "var(--task-state-active)" },
		],
		createdAt: "2026-02-17T11:00:00Z",
		updatedAt: "2026-02-22T14:00:00Z",
	},
	{
		id: "d5",
		identifier: "MAS-38",
		title: "Design system: unify button variants across app",
		state: DEMO_STATES[1],
		priority: 3,
		url: "#",
		labels: [{ name: "design", color: "var(--task-label-workflow)" }],
		assignee: { name: "Alex", displayName: "Alex" },
		createdAt: "2026-02-16T16:00:00Z",
		updatedAt: "2026-02-21T10:00:00Z",
	},
	{
		id: "d6",
		identifier: "MAS-37",
		title: "Support custom model providers via plugin system",
		state: DEMO_STATES[0],
		priority: 3,
		url: "#",
		labels: [{ name: "feature", color: "var(--task-label-feature)" }],
		createdAt: "2026-02-15T08:00:00Z",
		updatedAt: "2026-02-20T09:00:00Z",
	},
	{
		id: "d7",
		identifier: "MAS-36",
		title: "Write integration tests for workflow engine",
		state: DEMO_STATES[0],
		priority: 4,
		url: "#",
		labels: [{ name: "testing", color: "var(--task-label-testing)" }],
		createdAt: "2026-02-14T13:00:00Z",
		updatedAt: "2026-02-19T11:00:00Z",
	},
	{
		id: "d8",
		identifier: "MAS-35",
		title: "Migrate auth tokens to secure keychain storage",
		state: DEMO_STATES[4],
		priority: 2,
		url: "#",
		labels: [{ name: "security", color: "var(--task-label-bug)" }],
		assignee: { name: "Grayson", displayName: "Grayson" },
		createdAt: "2026-02-10T10:00:00Z",
		updatedAt: "2026-02-18T15:00:00Z",
	},
	{
		id: "d9",
		identifier: "MAS-34",
		title: "Add webhook support for workflow triggers",
		state: DEMO_STATES[4],
		priority: 3,
		url: "#",
		labels: [
			{ name: "feature", color: "var(--task-label-feature)" },
			{ name: "workflows", color: "var(--task-label-workflow)" },
		],
		assignee: { name: "Dax", displayName: "Dax" },
		createdAt: "2026-02-08T09:00:00Z",
		updatedAt: "2026-02-16T17:00:00Z",
	},
	{
		id: "d10",
		identifier: "MAS-33",
		title: "Update onboarding flow with interactive tutorial",
		state: DEMO_STATES[1],
		priority: 3,
		url: "#",
		labels: [
			{ name: "design", color: "var(--task-label-workflow)" },
			{ name: "ux", color: "var(--task-label-agent)" },
		],
		createdAt: "2026-02-12T14:00:00Z",
		updatedAt: "2026-02-20T12:00:00Z",
	},
]
