import type { LinearIssue, LinearState } from "../../types/taskboard"

export const PRIORITY_LABELS: Record<number, { label: string; color: string }> =
	{
		0: { label: "No priority", color: "var(--dim)" },
		1: { label: "Urgent", color: "#ef4444" },
		2: { label: "High", color: "#f97316" },
		3: { label: "Medium", color: "#eab308" },
		4: { label: "Low", color: "#6b7280" },
	}

export const STATE_TYPE_ORDER = [
	"backlog",
	"unstarted",
	"started",
	"completed",
	"cancelled",
]

export const DEMO_STATES: LinearState[] = [
	{ id: "s1", name: "Backlog", color: "#bec2c8", type: "backlog", position: 0 },
	{ id: "s2", name: "Todo", color: "#e2e2e2", type: "unstarted", position: 0 },
	{
		id: "s3",
		name: "In Progress",
		color: "#f2c94c",
		type: "started",
		position: 0,
	},
	{
		id: "s4",
		name: "In Review",
		color: "#f2994a",
		type: "started",
		position: 1,
	},
	{ id: "s5", name: "Done", color: "#5e6ad2", type: "completed", position: 0 },
	{
		id: "s6",
		name: "Cancelled",
		color: "#95a2b3",
		type: "cancelled",
		position: 0,
	},
]

export const DEMO_ISSUES: LinearIssue[] = [
	{
		id: "d1",
		identifier: "MAS-42",
		title: "Add tool-use streaming to agent responses",
		state: DEMO_STATES[2],
		priority: 1,
		url: "#",
		labels: [
			{ name: "feature", color: "#5e6ad2" },
			{ name: "agents", color: "#26b5ce" },
		],
		assignee: { name: "Grayson", displayName: "Grayson" },
		createdAt: "2026-02-20T10:00:00Z",
		updatedAt: "2026-02-24T09:00:00Z",
	},
	{
		id: "d2",
		identifier: "MAS-41",
		title: "Implement RAG pipeline with pgvector embeddings",
		state: DEMO_STATES[2],
		priority: 2,
		url: "#",
		labels: [
			{ name: "feature", color: "#5e6ad2" },
			{ name: "rag", color: "#f2994a" },
		],
		assignee: { name: "Grayson", displayName: "Grayson" },
		createdAt: "2026-02-19T14:00:00Z",
		updatedAt: "2026-02-23T16:00:00Z",
	},
	{
		id: "d3",
		identifier: "MAS-40",
		title: "Fix memory leak in long-running workflow executions",
		state: DEMO_STATES[3],
		priority: 1,
		url: "#",
		labels: [
			{ name: "bug", color: "#eb5757" },
			{ name: "workflows", color: "#bb6bd9" },
		],
		assignee: { name: "Dax", displayName: "Dax" },
		createdAt: "2026-02-18T09:00:00Z",
		updatedAt: "2026-02-24T08:00:00Z",
	},
	{
		id: "d4",
		identifier: "MAS-39",
		title: "Add retry logic to MCP tool connections",
		state: DEMO_STATES[1],
		priority: 2,
		url: "#",
		labels: [
			{ name: "enhancement", color: "#27ae60" },
			{ name: "mcp", color: "#f2c94c" },
		],
		createdAt: "2026-02-17T11:00:00Z",
		updatedAt: "2026-02-22T14:00:00Z",
	},
	{
		id: "d5",
		identifier: "MAS-38",
		title: "Design system: unify button variants across app",
		state: DEMO_STATES[1],
		priority: 3,
		url: "#",
		labels: [{ name: "design", color: "#bb6bd9" }],
		assignee: { name: "Alex", displayName: "Alex" },
		createdAt: "2026-02-16T16:00:00Z",
		updatedAt: "2026-02-21T10:00:00Z",
	},
	{
		id: "d6",
		identifier: "MAS-37",
		title: "Support custom model providers via plugin system",
		state: DEMO_STATES[0],
		priority: 3,
		url: "#",
		labels: [{ name: "feature", color: "#5e6ad2" }],
		createdAt: "2026-02-15T08:00:00Z",
		updatedAt: "2026-02-20T09:00:00Z",
	},
	{
		id: "d7",
		identifier: "MAS-36",
		title: "Write integration tests for workflow engine",
		state: DEMO_STATES[0],
		priority: 4,
		url: "#",
		labels: [{ name: "testing", color: "#6fcf97" }],
		createdAt: "2026-02-14T13:00:00Z",
		updatedAt: "2026-02-19T11:00:00Z",
	},
	{
		id: "d8",
		identifier: "MAS-35",
		title: "Migrate auth tokens to secure keychain storage",
		state: DEMO_STATES[4],
		priority: 2,
		url: "#",
		labels: [{ name: "security", color: "#eb5757" }],
		assignee: { name: "Grayson", displayName: "Grayson" },
		createdAt: "2026-02-10T10:00:00Z",
		updatedAt: "2026-02-18T15:00:00Z",
	},
	{
		id: "d9",
		identifier: "MAS-34",
		title: "Add webhook support for workflow triggers",
		state: DEMO_STATES[4],
		priority: 3,
		url: "#",
		labels: [
			{ name: "feature", color: "#5e6ad2" },
			{ name: "workflows", color: "#bb6bd9" },
		],
		assignee: { name: "Dax", displayName: "Dax" },
		createdAt: "2026-02-08T09:00:00Z",
		updatedAt: "2026-02-16T17:00:00Z",
	},
	{
		id: "d10",
		identifier: "MAS-33",
		title: "Update onboarding flow with interactive tutorial",
		state: DEMO_STATES[1],
		priority: 3,
		url: "#",
		labels: [
			{ name: "design", color: "#bb6bd9" },
			{ name: "ux", color: "#26b5ce" },
		],
		createdAt: "2026-02-12T14:00:00Z",
		updatedAt: "2026-02-20T12:00:00Z",
	},
]
